title: 'Kaypuna Indonesia'
default_lang: en
author:
  name: kaypuna
  email: kaypunainc@hotmail.com
taxonomies:
  - category
  - tag
metadata:
  description: 'kaypuna  , save planet earth  enviromental and climate change '
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
